<?php
/**
 * InlineResponse200
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace GoogleApi\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse200 model.
 *
 * @package GoogleApi\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse200 
{
        /**
     * @var GoogleApi\Server\Model\PlusCode|null
     * @SerializedName("plus_code")
     * @Assert\Type("GoogleApi\Server\Model\PlusCode")
     * @Type("GoogleApi\Server\Model\PlusCode")
     */
    protected $plusCode;

    /**
     * @var GoogleApi\Server\Model\InlineResponse200Results[]|null
     * @SerializedName("results")
     * @Assert\All({
     *   @Assert\Type("GoogleApi\Server\Model\InlineResponse200Results")
     * })
     * @Type("array<GoogleApi\Server\Model\InlineResponse200Results>")
     */
    protected $results;

    /**
     * @var string|null
     * @SerializedName("status")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $status;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->plusCode = isset($data['plusCode']) ? $data['plusCode'] : null;
        $this->results = isset($data['results']) ? $data['results'] : null;
        $this->status = isset($data['status']) ? $data['status'] : null;
    }

    /**
     * Gets plusCode.
     * @return GoogleApi\Server\Model\PlusCode|null
     */
    public function getPlusCode() 
    {
        return $this->plusCode;
    }

    /**
     * Sets plusCode.
     *
     * @param GoogleApi\Server\Model\PlusCode|null $plusCode
     * 
     * @return $this
     */
    public function setPlusCode(PlusCode $plusCode = null)
    {
        $this->plusCode = $plusCode;

        return $this;
    }

    /**
     * Gets results.
     * @return GoogleApi\Server\Model\InlineResponse200Results[]|null
     */
    public function getResults() 
    {
        return $this->results;
    }

    /**
     * Sets results.
     *
     * @param GoogleApi\Server\Model\InlineResponse200Results[]|null $results
     * 
     * @return $this
     */
    public function setResults(array $results = null)
    {
        $this->results = $results;

        return $this;
    }

    /**
     * Gets status.
     * @return string|null
     */
    public function getStatus() 
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status
     * 
     * @return $this
     */
    public function setStatus( $status = null)
    {
        $this->status = $status;

        return $this;
    }
}


