<?php
/**
 * Viewport
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace GoogleApi\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Viewport model.
 *
 * @package GoogleApi\Server\Model
 * @author  Swagger Codegen team
 */
class Viewport 
{
        /**
     * @var GoogleApi\Server\Model\Location|null
     * @SerializedName("northeast")
     * @Assert\Type("GoogleApi\Server\Model\Location")
     * @Type("GoogleApi\Server\Model\Location")
     */
    protected $northeast;

    /**
     * @var GoogleApi\Server\Model\Location|null
     * @SerializedName("southwest")
     * @Assert\Type("GoogleApi\Server\Model\Location")
     * @Type("GoogleApi\Server\Model\Location")
     */
    protected $southwest;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->northeast = isset($data['northeast']) ? $data['northeast'] : null;
        $this->southwest = isset($data['southwest']) ? $data['southwest'] : null;
    }

    /**
     * Gets northeast.
     * @return GoogleApi\Server\Model\Location|null
     */
    public function getNortheast() 
    {
        return $this->northeast;
    }

    /**
     * Sets northeast.
     *
     * @param GoogleApi\Server\Model\Location|null $northeast
     * 
     * @return $this
     */
    public function setNortheast(Location $northeast = null)
    {
        $this->northeast = $northeast;

        return $this;
    }

    /**
     * Gets southwest.
     * @return GoogleApi\Server\Model\Location|null
     */
    public function getSouthwest() 
    {
        return $this->southwest;
    }

    /**
     * Sets southwest.
     *
     * @param GoogleApi\Server\Model\Location|null $southwest
     * 
     * @return $this
     */
    public function setSouthwest(Location $southwest = null)
    {
        $this->southwest = $southwest;

        return $this;
    }
}


