<?php
/**
 * AddressComponentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 1.0.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GoogleApi\Server\Model;

/**
 * AddressComponentTest Class Doc Comment
 *
 * @category    Class */
// * @description AddressComponent
/**
 * @package     GoogleApi\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressComponentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddressComponent"
     */
    public function testAddressComponent()
    {
        $testAddressComponent = new AddressComponent();
    }

    /**
     * Test attribute "longName"
     */
    public function testPropertyLongName()
    {
    }

    /**
     * Test attribute "shortName"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "types"
     */
    public function testPropertyTypes()
    {
    }
}
