<?php
/**
 * GeometryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GoogleApi\Server\Model;

/**
 * GeometryTest Class Doc Comment
 *
 * @category    Class */
// * @description Geometry
/**
 * @package     GoogleApi\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GeometryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Geometry"
     */
    public function testGeometry()
    {
        $testGeometry = new Geometry();
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "locationType"
     */
    public function testPropertyLocationType()
    {
    }

    /**
     * Test attribute "viewport"
     */
    public function testPropertyViewport()
    {
    }
}
