<?php
/**
 * PlusCodeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GoogleApi\Server\Model;

/**
 * PlusCodeTest Class Doc Comment
 *
 * @category    Class */
// * @description PlusCode
/**
 * @package     GoogleApi\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlusCodeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlusCode"
     */
    public function testPlusCode()
    {
        $testPlusCode = new PlusCode();
    }

    /**
     * Test attribute "compoundCode"
     */
    public function testPropertyCompoundCode()
    {
    }

    /**
     * Test attribute "globalCode"
     */
    public function testPropertyGlobalCode()
    {
    }
}
