<?php
/**
 * GeocodeApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace GoogleApi\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use GoogleApi\Server\Model\InlineResponse200;

/**
 * GeocodeApiInterface Interface Doc Comment
 * Base interface for the class
 * @category Interface
 * @package  GoogleApi\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface GeocodeApiInterfaceBase extends ApiInterfaceCommonBase
{    
}
